driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: package
  run_list:
  - recipe[test::default]
- name: binary
  run_list:
  - recipe[test::binary]
- name: source
  run_list:
  - recipe[test::source]
  excludes:
    - centos-6
- name: npm
  run_list:
  - recipe[test::npm]
- name: npm_embedded
  run_list:
  - recipe[test::npm]
  attributes:
    nodejs:
      npm:
        install_method: embedded
- name: npm_source
  run_list:
  - recipe[test::npm]
  attributes:
    nodejs:
      npm:
        install_method: source
  excludes:
    - centos-6
- name: npm_packages
  run_list: recipe[nodejs]
  attributes:
    nodejs:
      npm_packages:
        - name: express
        - name: socket.io
          version: 1.0.4
        - name: express
          action: uninstall
