---
PreCommit:
  TrailingWhitespace:
    enabled: true
  YamlLint:
    enabled: true
  ChefSpec:
    enabled: true
    command: ["chef", "exec", "rspec"]
  Cookstyle:
    enabled: true
    required_executable: "cookstyle"
    command: ["cookstyle"]
  MarkdownLint:
    enabled: false
    command: ["echo $HOME", "npx", "markdownlint-cli2", "'**/*.md'"]
    include: ["**/*.md"]

CommitMsg:
  HardTabs:
    enabled: true
