# frozen_string_literal: true

name              'nodejs'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides resources for installing Node.js and managing npm packages'
version           '11.0.0'
source_url        'https://github.com/sous-chefs/nodejs'
issues_url        'https://github.com/sous-chefs/nodejs/issues'
chef_version      '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'mac_os_x'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
supports 'windows'

depends 'ark', '>= 2.0.2'
depends 'chocolatey', '>= 3.0'
depends 'yum', '>= 7.2'
