---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0
    permissions:
      contents: read
      checks: write
      pull-requests: write
      statuses: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "almalinux-8"
          - "almalinux-9"
          - "almalinux-10"
          - "rockylinux-9"
          - "amazonlinux-2023"
          - "centos-stream-9"
          - "centos-stream-10"
          - "debian-12"
          - "debian-13"
          - "fedora-latest"
          - "oraclelinux-8"
          - "oraclelinux-9"
          - "rockylinux-8"
          - "rockylinux-10"
          - "ubuntu-2204"
          - "ubuntu-2404"
        suite:
          - "default"
          - "npm-embedded"
          - "package"
          - "source"
        exclude:
          - os: "amazonlinux-2023"
            suite: "source"
          - os: "fedora-latest"
            suite: "source"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Chef
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  success:
    if: ${{ always() }}
    needs: ["integration"]
    name: Integration Successful
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        name: Check matrix status
        run: exit 1
